---
output: html_document
---

# To Do

+ Frequency Table 1 - add row "Total", showing the total number of subjects in each study, 100% of all subjects
    - change to samples
    - make patient table
    - use upsetR package to make plot of body site by patient
    - histogram of patients by visit number
    

- Make three frequency histograms of visits, one for each study. **Each bin should represent one visit type, i.e., show how many are "visit 1", "visit 2", etc.** - **geom_histogram(bins = 15)** IS WRONG!
    - Make the histograms nicer. Put them on a single plot. Color studies differently. Look at http://www.sthda.com/english/wiki/ggplot2-histogram-plot-quick-start-guide-r-software-and-data-visualization for good examples
    - The final product should look something like: http://www.sthda.com/sthda/RDoc/figure/ggplot2/ggplot2-histogram-change-group-colors-interleaved-data-visualization-1.png

- Describe in the vignette how to invoke vignettes. `browseVignettes("HMP2Data")` doesn't work.
    - Even after installing like: `devtools::install_github("jstansfield0/HMP2Data", auth_token = "e1ef7c328f2c14b2627ad113093b65726f9e24d3", build_vignettes = TRUE)`, vignettes still cannot be found:
```
> library(HMP2Data)
> browseVignettes("HMP2Data")
No vignettes found by browseVignettes("HMP2Data")
```

- check HMP16SData


- Create a vignette about data processing. Include processing scripts as non-exportable files.
    - From `mdozmorov/HMP2` repository, use `preprocess_biom_16S.Rmd`, `preprocess_phyloseq_16S.Rmd`, `preprocess_cytokines.Rmd`, `read_ibd_t2d_biom.Rmd`.
    - Reorganize the code into a more streamlined set of files, rename, split, combine files, as appropriate.
    - Make the code generic, e.g., remove absolute paths, add `path/to/something` with comments.
    - Describe the use of these files in the vignette.
