---
title: "read IBD and T2D biom files"
author: "author"
date: "January 11, 2019"
output: html_document
---

# T2D

# Settings

You will need to change the paths to the data locations.

```{r}
library(phyloseq)
library(dplyr)
library(readr)
library(magrittr)

options(stringsAsFactors = FALSE)
# Input files
# Change paths to your data directory
dataDir <- "data.T2D/t2d/" # path to folder containing data files
fileNameIn1  <- "data.T2D/hmp_cart_50199a791.tsv" # Manifest
fileNameIn2  <- "data.T2D/hmp_cart_metadata_12019e21a0.tsv" # Metadata
T2DFileOut <- "data/hmp2_phyloseq_16S_T2D.rda"
files <- list.files("data.T2D/t2d") # data file list
green <- read.table("data/gg_13_5_taxonomy.txt", sep = "\t") # greengenes taxonomy file
```

# Read data

```{r}
# Manifest
mtx1 <- read_tsv(fileNameIn1)
# Add file names
mtx1 %<>% mutate(file_name = sapply(mtx1$urls, function(x) strsplit(x, split = ",", fixed = TRUE)[[1]][1] %>% basename) %>% unname)
mtx2 <- read_tsv(fileNameIn2)
mtx1 <- left_join(mtx1, mtx2, by = c("sample_id"))

# Sanity check: Are they all in the manifest?
all.equal(files %>% basename %>% sort, mtx1$file_name %>% sort)

phylo_list <- list()

# import biom files
for(i in 1:length(files)) {
  phylo_list[[i]] <- import_biom(paste0(dataDir, files[i]))
}


# Merge data
mat <- otu_table(phylo_list[[1]])
mat <- data.frame(taxa = as.numeric(rownames(mat)), counts = mat[,1])
for (i in 2:length(phylo_list)) {
  tmp <- otu_table(phylo_list[[i]])
  tmp <- data.frame(taxa = as.numeric(rownames(tmp)), counts = tmp[,1])
  mat <- full_join(mat, tmp, by = c("taxa" = "taxa"))
}

rownames(mat) <- mat$taxa
colnames(mat)[-1] <- files
mat[is.na(mat)] <- 0
mat.taxa <- mat$taxa
mat <- mat[,-1]
mat <- as.matrix(mat)
# get which files are in metadata
idx <- match(files, mtx1$file_name)


```

## Tax table


```{r}
# Make taxonomy table
# Get taxonomy column
mtx_tax_table <- as.character(green$V2)
# Split the combined strings, and combine them into data frame
mtx_tax_table <- sapply(mtx_tax_table, function(x) strsplit(x, "; ")) %>% unname %>% do.call(rbind, .)


# A function to take column i, extract taxa level prefix, return unique prefixes
# Made for sanity check - each column should return only one taxa level ID
check_taxa_level <- function(mtx_tax_table, i) {
  sapply(mtx_tax_table[, i], function(x) strsplit(x, "__")[[1]][1]) %>% unname %>% unique
}
# Actually do sanity check - should be single letters corresponding to
# Kingdom   Phylum          Class          Order          Family          Genus        Species
for (i in 1:ncol(mtx_tax_table)) {
  check_taxa_level(mtx_tax_table = mtx_tax_table, i) %>% print
}

# A function to take a column and remove taxa level prefix from it
prune_taxa_level <- function(column) {
  sapply(column, function(x) strsplit(x, "__")[[1]][2]) %>% unname
}
# Actually remove prefixes from the columns
mtx_tax_table <- apply(mtx_tax_table, 2, function(x) prune_taxa_level(x))

# Attach column and row names
colnames(mtx_tax_table) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species") # Fixed names
rownames(mtx_tax_table) <- green$V1 # Greengene IDs
mtx_tax_table[1:5, 1:5]
```

## make phyloseq object

```{r}
meta <- as.data.frame(mtx1[idx,])
rownames(meta) <- meta$file_name

otu <- otu_table(mat, taxa_are_rows = TRUE)
samp <- sample_data(meta)
samp <- samp[, c('file_id', 'sample_id', 'file_name', 'subject_id', 'sample_body_site', "visit_number" ,
               "subject_gender",   "subject_race" ,    "study_full_name" , "project_name"   )]

# order everything
# tax.idx <- match(as.numeric(rownames(mtx_tax_table)), as.numeric(rownames(mat)))
# tax.idx <- tax.idx[!is.na(tax.idx)]
taxa <- mtx_tax_table#[order(tax.idx),]
taxa <- tax_table(taxa)
# taxa <- taxa[order(rownames(taxa)),]
# otu <- otu[order(rownames(otu)), ]

T2D_phyloseq <- phyloseq(otu, samp, taxa)
save(T2D_phyloseq, file = T2DFileOut)
```



