---
title: "Making phyloseq object"
# author: "Author's Name"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r libraries}
library(phyloseq)
```

# Settings

You will need to change the paths to the data locations.

```{r}
# Input file name
fileNameIn1  <- "data/hmp2_biom_16S_momspi.rda" # path to data saved from preprocess_biom16S.Rmd
# Output file name
fileNameOut1 <- "data/hmp2_phyloseq_16S_momspi.rda"
```

# Load data

```{r}
load(file = fileNameIn1)
```

# Make phyloseq object

```{r}
data("GlobalPatterns")
GlobalPatterns
otu_table(GlobalPatterns)[1:5, 1:5]
sample_data(GlobalPatterns)[1:5, 1:5]
tax_table(GlobalPatterns)[1:5, ]
?phyloseq
?otu_table
?sample_data
?tax_table
```

```{r}
mtx_biom_data[1:5, 1:5] # OTU table and tax table
mtx_metadata[1:5, 1:5]  # Sample data
# Order of samples in OTU table and Sample data should be the same
all.equal(mtx_metadata$file, colnames(mtx_biom_data)[grepl("EP", colnames(mtx_biom_data))])
```

```{r}
# Make OTU table
mtx_otu_table <- mtx_biom_data[, grepl("EP", colnames(mtx_biom_data))] # Select only columns with "EP*" sample names
rownames(mtx_otu_table) <- mtx_biom_data$ID # Rownames as Greengene IDs
mtx_otu_table[is.na(mtx_otu_table)] <- 0 # Replace NAs by zeros
mtx_otu_table[1:5, 1:5]
```

```{r}
# Make sample data
mtx_sample_data <- as.data.frame(mtx_metadata) # Full annotations
rownames(mtx_sample_data) <- mtx_metadata$file # Rownames as file IDs
```

```{r}
# Make taxonomy table
# Get taxonomy column
mtx_tax_table <- mtx_biom_data$Taxonomy
# Split the combined strings, and combine them into data frame
mtx_tax_table <- sapply(mtx_tax_table, function(x) strsplit(x, "; ")) %>% unname %>% do.call(rbind, .)

# A function to take column i, extract taxa level prefix, return unique prefixes
# Made for sanity check - each column should return only one taxa level ID
check_taxa_level <- function(mtx_tax_table, i) {
  sapply(mtx_tax_table[, i], function(x) strsplit(x, "__")[[1]][1]) %>% unname %>% unique
}
# Actually do sanity check - should be single letters corresponding to
# Kingdom   Phylum          Class          Order          Family          Genus        Species
for (i in 1:ncol(mtx_tax_table)) {
  check_taxa_level(mtx_tax_table = mtx_tax_table, i) %>% print
}

# A function to take a column and remove taxa level prefix from it
prune_taxa_level <- function(column) {
  sapply(column, function(x) strsplit(x, "__")[[1]][2]) %>% unname
}
# Actually remove prefixes from the columns
mtx_tax_table <- apply(mtx_tax_table, 2, function(x) prune_taxa_level(x))

# Attach column and row names
colnames(mtx_tax_table) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species") # Fixed names
rownames(mtx_tax_table) <- mtx_biom_data$ID # Greengene IDs
mtx_tax_table[1:5, 1:5]
```

```{r}
mtx_phyloseq_16S <- phyloseq(otu_table(mtx_otu_table, taxa_are_rows = TRUE),
                             sample_data(mtx_sample_data),
                             tax_table(mtx_tax_table))
mtx_phyloseq_16S
save(list = c("mtx_phyloseq_16S"), file = fileNameOut1)
```

